kind: Service
apiVersion: v1
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: expense
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80