kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ebs-dynamic-claim
spec:
  storageClassName: "expense-ebs"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
# pod
kind: Pod
apiVersion: v1
metadata:
  name: nginx-dynamic
  labels:
    purpose: ebs-dynamic
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic-claim

